#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <model_path>"
  echo
  echo "Example:"
  echo "  bash $0 ~/models/Qwen3-0.6B/"
  echo
  echo "Optional environment variables:"
  echo "  PYTHON_BIN=python3"
  echo "  LOG_ROOT=logs/full_bench_YYYYmmdd_HHMMSS"
  echo "  REPEAT=5"
  echo "  NUM_SEQS=128"
  echo "  SEED=0"
  echo "  VOCAB_SIZE=10000"
  echo "  MIN_INPUT_LEN=100"
  echo "  MAX_INPUT_LEN=1024"
  echo "  MIN_OUTPUT_LEN=32"
  echo "  MAX_OUTPUT_LEN=128"
  echo "  SHARED_PREFIX_LEN=768"
  echo "  TEMPERATURE=0.6"
  echo "  MAX_MODEL_LEN=4096"
  echo "  MAX_NUM_BATCHED_TOKENS=16384"
  echo "  MAX_NUM_SEQS=512"
  echo "  GPU_MEMORY_UTILIZATION=0.9"
  echo "  KVCACHE_BLOCK_SIZE=256"
  echo "  PREFILL_CHUNK_SIZE=1024"
  echo "  MAX_SEQ_LEN_TO_CAPTURE=4096"
  echo "  RUN_EAGER=0"
  exit 2
fi

MODEL_PATH="$1"
PYTHON_BIN="${PYTHON_BIN:-python3}"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_ROOT="${LOG_ROOT:-logs/full_bench_${TIMESTAMP}}"

REPEAT="${REPEAT:-5}"
NUM_SEQS="${NUM_SEQS:-128}"
SEED="${SEED:-0}"
VOCAB_SIZE="${VOCAB_SIZE:-10000}"
MIN_INPUT_LEN="${MIN_INPUT_LEN:-100}"
MAX_INPUT_LEN="${MAX_INPUT_LEN:-1024}"
MIN_OUTPUT_LEN="${MIN_OUTPUT_LEN:-32}"
MAX_OUTPUT_LEN="${MAX_OUTPUT_LEN:-128}"
SHARED_PREFIX_LEN="${SHARED_PREFIX_LEN:-768}"
TEMPERATURE="${TEMPERATURE:-0.6}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-4096}"
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-16384}"
MAX_NUM_SEQS="${MAX_NUM_SEQS:-512}"
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.9}"
KVCACHE_BLOCK_SIZE="${KVCACHE_BLOCK_SIZE:-256}"
PREFILL_CHUNK_SIZE="${PREFILL_CHUNK_SIZE:-1024}"
MAX_SEQ_LEN_TO_CAPTURE="${MAX_SEQ_LEN_TO_CAPTURE:-4096}"
RUN_EAGER="${RUN_EAGER:-0}"

mkdir -p "$LOG_ROOT"

ENV_LOG="${LOG_ROOT}/env.log"
{
  echo "timestamp=${TIMESTAMP}"
  echo "cwd=$(pwd)"
  echo "model_path=${MODEL_PATH}"
  echo "python_bin=${PYTHON_BIN}"
  echo "git_commit=$(git rev-parse HEAD 2>/dev/null || echo unknown)"
  echo "git_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
  echo
  echo "[git status]"
  git status --short 2>/dev/null || true
  echo
  echo "[python]"
  "${PYTHON_BIN}" --version
  echo
  echo "[torch/cuda]"
  "${PYTHON_BIN}" - <<'PY' || true
import json
try:
    import torch
    info = {
        "torch": torch.__version__,
        "cuda_available": torch.cuda.is_available(),
        "cuda": getattr(torch.version, "cuda", None),
        "device_count": torch.cuda.device_count() if torch.cuda.is_available() else 0,
        "devices": [
            torch.cuda.get_device_name(i)
            for i in range(torch.cuda.device_count())
        ] if torch.cuda.is_available() else [],
    }
except Exception as exc:
    info = {"error": repr(exc)}
print(json.dumps(info, indent=2, sort_keys=True))
PY
  echo
  echo "[nvidia-smi]"
  nvidia-smi || true
  echo
  echo "[benchmark defaults]"
  echo "repeat=${REPEAT}"
  echo "num_seqs=${NUM_SEQS}"
  echo "seed=${SEED}"
  echo "vocab_size=${VOCAB_SIZE}"
  echo "min_input_len=${MIN_INPUT_LEN}"
  echo "max_input_len=${MAX_INPUT_LEN}"
  echo "min_output_len=${MIN_OUTPUT_LEN}"
  echo "max_output_len=${MAX_OUTPUT_LEN}"
  echo "shared_prefix_len=${SHARED_PREFIX_LEN}"
  echo "temperature=${TEMPERATURE}"
  echo "max_model_len=${MAX_MODEL_LEN}"
  echo "max_num_batched_tokens=${MAX_NUM_BATCHED_TOKENS}"
  echo "max_num_seqs=${MAX_NUM_SEQS}"
  echo "gpu_memory_utilization=${GPU_MEMORY_UTILIZATION}"
  echo "kvcache_block_size=${KVCACHE_BLOCK_SIZE}"
  echo "prefill_chunk_size=${PREFILL_CHUNK_SIZE}"
  echo "max_seq_len_to_capture=${MAX_SEQ_LEN_TO_CAPTURE}"
  echo "run_eager=${RUN_EAGER}"
} | tee "$ENV_LOG"

COMMON_ARGS=(
  --model "$MODEL_PATH"
  --seed "$SEED"
  --num-seqs "$NUM_SEQS"
  --vocab-size "$VOCAB_SIZE"
  --min-input-len "$MIN_INPUT_LEN"
  --max-input-len "$MAX_INPUT_LEN"
  --min-output-len "$MIN_OUTPUT_LEN"
  --max-output-len "$MAX_OUTPUT_LEN"
  --shared-prefix-len "$SHARED_PREFIX_LEN"
  --temperature "$TEMPERATURE"
  --max-model-len "$MAX_MODEL_LEN"
  --max-num-batched-tokens "$MAX_NUM_BATCHED_TOKENS"
  --max-num-seqs "$MAX_NUM_SEQS"
  --gpu-memory-utilization "$GPU_MEMORY_UTILIZATION"
  --kvcache-block-size "$KVCACHE_BLOCK_SIZE"
  --prefill-chunk-size "$PREFILL_CHUNK_SIZE"
  --max-seq-len-to-capture "$MAX_SEQ_LEN_TO_CAPTURE"
  --repeat "$REPEAT"
)

WORKLOADS=(random mixed_lengths shared_prefix)
VARIANTS=(baseline fair late_merge optimized)
if [[ "$RUN_EAGER" == "1" ]]; then
  VARIANTS+=(baseline_eager optimized_eager)
fi

write_command_file() {
  local cmd_file="$1"
  shift
  {
    echo "#!/usr/bin/env bash"
    echo "set -euo pipefail"
    echo
    echo "# Generated by scripts/run_full_bench_matrix.sh"
    echo "# timestamp=${TIMESTAMP}"
    echo "# git_commit=$(git rev-parse HEAD 2>/dev/null || echo unknown)"
    echo "# model_path=${MODEL_PATH}"
    echo "# repeat=${REPEAT}"
    echo "# num_seqs=${NUM_SEQS}"
    echo "# max_model_len=${MAX_MODEL_LEN}"
    echo "# max_num_batched_tokens=${MAX_NUM_BATCHED_TOKENS}"
    echo "# kvcache_block_size=${KVCACHE_BLOCK_SIZE}"
    echo "# prefill_chunk_size=${PREFILL_CHUNK_SIZE}"
    echo
    printf "%q " "$@"
    echo
  } > "$cmd_file"
  chmod +x "$cmd_file"
}

run_case() {
  local workload="$1"
  local variant="$2"
  local label="${workload}__${variant}__seq${NUM_SEQS}__rep${REPEAT}__tok${MAX_NUM_BATCHED_TOKENS}__blk${KVCACHE_BLOCK_SIZE}__chunk${PREFILL_CHUNK_SIZE}"
  local jsonl_file="${LOG_ROOT}/${label}.jsonl"
  local log_file="${LOG_ROOT}/${label}.log"
  local cmd_file="${LOG_ROOT}/${label}.cmd.sh"
  local meta_file="${LOG_ROOT}/${label}.meta.txt"

  local run_label="$variant"
  if [[ "$variant" == "baseline_eager" ]]; then
    run_label="baseline"
  elif [[ "$variant" == "optimized_eager" ]]; then
    run_label="optimized"
  fi

  local cmd=(
    "$PYTHON_BIN" bench.py
    "${COMMON_ARGS[@]}"
    --workload "$workload"
    --run-label "$run_label"
    --output-jsonl "$jsonl_file"
  )

  case "$variant" in
    baseline)
      cmd+=(--mode baseline --prefill-policy fcfs)
      ;;
    fair)
      cmd+=(--mode baseline --prefill-policy fair)
      ;;
    late_merge)
      cmd+=(--mode baseline --prefill-policy fcfs --enable-prefix-late-merge)
      ;;
    optimized)
      cmd+=(--mode optimized)
      ;;
    baseline_eager)
      cmd+=(--mode baseline --prefill-policy fcfs --enforce-eager)
      ;;
    optimized_eager)
      cmd+=(--mode optimized --enforce-eager)
      ;;
    *)
      echo "Unknown variant: $variant" >&2
      exit 2
      ;;
  esac

  write_command_file "$cmd_file" "${cmd[@]}"

  {
    echo "workload=${workload}"
    echo "variant=${variant}"
    echo "jsonl_file=${jsonl_file}"
    echo "log_file=${log_file}"
    echo "cmd_file=${cmd_file}"
    echo "timestamp=${TIMESTAMP}"
    echo "git_commit=$(git rev-parse HEAD 2>/dev/null || echo unknown)"
    echo "model_path=${MODEL_PATH}"
    echo "repeat=${REPEAT}"
    echo "num_seqs=${NUM_SEQS}"
    echo "seed=${SEED}"
    echo "max_model_len=${MAX_MODEL_LEN}"
    echo "max_num_batched_tokens=${MAX_NUM_BATCHED_TOKENS}"
    echo "kvcache_block_size=${KVCACHE_BLOCK_SIZE}"
    echo "prefill_chunk_size=${PREFILL_CHUNK_SIZE}"
    echo
    echo "[command]"
    printf "%q " "${cmd[@]}"
    echo
  } > "$meta_file"

  {
    echo "============================================================"
    echo "Running workload=${workload} variant=${variant}"
    echo "Log: ${log_file}"
    echo "JSONL: ${jsonl_file}"
    echo "Command file: ${cmd_file}"
    echo "Meta file: ${meta_file}"
    echo "============================================================"
    echo
    cat "$meta_file"
    echo
    echo "[benchmark output]"
    "${cmd[@]}"
  } 2>&1 | tee "$log_file"
}

README_FILE="${LOG_ROOT}/README.txt"
{
  echo "Full nano-VLLM benchmark run"
  echo
  echo "Created at: ${TIMESTAMP}"
  echo "Model: ${MODEL_PATH}"
  echo "Git commit: $(git rev-parse HEAD 2>/dev/null || echo unknown)"
  echo
  echo "For each case, files are named as:"
  echo "  <workload>__<variant>__seq<NUM_SEQS>__rep<REPEAT>__tok<MAX_NUM_BATCHED_TOKENS>__blk<KVCACHE_BLOCK_SIZE>__chunk<PREFILL_CHUNK_SIZE>.*"
  echo
  echo "File meanings:"
  echo "  *.cmd.sh   exact command that was run"
  echo "  *.meta.txt command metadata and key config"
  echo "  *.log      full tee output"
  echo "  *.jsonl    raw per-repeat benchmark JSON records"
  echo "  env.log    environment, git, Python, torch, CUDA and nvidia-smi info"
  echo
  echo "Workloads: ${WORKLOADS[*]}"
  echo "Variants: ${VARIANTS[*]}"
} | tee "$README_FILE"

for workload in "${WORKLOADS[@]}"; do
  for variant in "${VARIANTS[@]}"; do
    run_case "$workload" "$variant"
  done
done

echo
echo "All benchmark cases completed."
echo "Logs are under: ${LOG_ROOT}"
echo "Environment log: ${ENV_LOG}"
echo "README: ${README_FILE}"
